### ISSUE TITLE
Stereo calibration crashes wtihout a warning

### ISSUE THREAD

**Issue by Legor** [i3drobotics/stereo-vision-toolkit#79] opened 2021-06-16 08:19 UTC
Software version: v1.3.1.2 
Os: Win 10 64Bit  

I have been trying to use the stereo calibration so far but didn't succeed. 
When providing the folders of the left and right images and pressing "Find images", all the images are listed correctly, however the Ok Button to start the calibration is greyed out afterwards, and can not be clicked.

When doing the same, without pressing "Find images" first, the button is still active, however when I click it the whole application crashes without any further error message or notice.

May this be related to my image format? I'm using 8bit single channel (grayscale) JPG images.
Is there a way to get more detailed debug output from your application (e.g. openCV exceptions)?

**Comment by benknight135** [comment] 2021-06-16 08:48
Thank you for reporting this issue, I will look into it today. To read the images they are automatically converted/read to a grayscale image using OpenCV's imread function with the 'IMREAD_GRAYSCALE' option so your images format shouldn't cause issues. 
```
cv::Mat im = cv::imread(image_path, cv::IMREAD_GRAYSCALE);
```

Would you be able to provide the data you are using for the calibration to assist in diagnosing this issue? 
If this is sensitive data then you can send it via email to bknight@i3drobotics.com.

**Comment by Legor** [comment] 2021-06-16 08:52
Yes, I can send you some example images to the aforementioned mail.
Thanks for taking time to look into this.

**Comment by benknight135** [comment] 2021-06-16 10:47
I have created specific issues to fix the causes of this issue and will update them as they are completed. I will create a new release once these issues are fixed.
## Issues
#80 - OK button in image calibration dialog enabled with invalid image file list
#81 - Crash when loading 5 image pair in image calibration dialog
#82 - Update documentation to clarify stereo calibration routine

**Comment by benknight135** [comment] 2021-06-16 13:53
fixed in v1.3.1.3

**Closed** 2021-06-16 13:53 UTC
Labels: bug
